###

POST http://localhost:5000/workout-plan
Content-type: application/json

{
    "planName": "Marathon3",
    "exercises": [
        {
            "name": "Running",
            "duration": "30 minutes"
        },
        {
            "name": "Yapping",
            "duration": "100 Yodels"
        }
    ]
}